/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumno;

import com.mycompany.loginpro.Administrador;
import com.mycompany.loginpro.LoginPro;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author leonardo.castanaza
 */
public class CargaAlumnoXML extends javax.swing.JFrame {
        
    /**
     * Creates new form CargaAlumnoXML
     */
    public CargaAlumnoXML() {
        initComponents();
        LoadTable();
        this.setTitle("Carga masiva de alumnos");
    }
    
    public void LoadTable(){
        DefaultTableModel CargaAlumno = new DefaultTableModel(new String[]{"#", "Carne", "Nombre", "Apellido","Password"}, LoginPro.alumnos.size());
        jTable1.setModel(CargaAlumno);    
        int row = 0;
        for (Alumno alumno : LoginPro.alumnos) {
            jTable1.setValueAt(row+1, row, 0);
            jTable1.setValueAt(alumno.carne, row, 1);
            jTable1.setValueAt(alumno.nombre, row, 2);
            jTable1.setValueAt(alumno.apellido, row, 3);
            jTable1.setValueAt(alumno.password, row, 4);
            row ++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBttnRegresar = new javax.swing.JButton();
        jBttnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBttnRegresar.setText("Regresar");
        jBttnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnRegresarActionPerformed(evt);
            }
        });

        jBttnCargar.setText("Carga Masiva XML");
        jBttnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBttnCargar)
                .addGap(18, 18, 18)
                .addComponent(jBttnRegresar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnRegresar)
                    .addComponent(jBttnCargar))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnRegresarActionPerformed
        Administrador a = new Administrador();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBttnRegresarActionPerformed

    private void jBttnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCargarActionPerformed
        JFileChooser archivo = new JFileChooser("");
        int seleccionar = archivo.showDialog(this, "Cargar");
        if (seleccionar==JFileChooser.APPROVE_OPTION) {
            leerArchivoXMLAlumnos(archivo.getSelectedFile());
        }
    }//GEN-LAST:event_jBttnCargarActionPerformed
        public void leerArchivoXMLAlumnos (File archivo){
        try {
            DocumentBuilderFactory Dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder Db = Dbf.newDocumentBuilder();
            Document doc = Db.parse(archivo);
            
            doc.getDocumentElement().normalize();
            NodeList nodos = doc.getElementsByTagName("alumno");
            for (int i = 0;i < nodos.getLength(); i++) {
                Node n = nodos.item(i);
                if (n.getNodeType()==Node.ELEMENT_NODE) {
                    Element e = (Element) n;
                    Alumno alumno = new Alumno();
                    alumno.carne = String.valueOf(e.getElementsByTagName("carne")
                            .item(0)
                            .getTextContent());
                    alumno.nombre = e.getElementsByTagName("nombre")
                            .item(0)
                            .getTextContent();
                    alumno.apellido = e.getElementsByTagName("apellido")
                            .item(0)
                            .getTextContent();
                    alumno.password = e.getElementsByTagName("password")
                            .item(0)
                            .getTextContent();
                    LoginPro.alumnos.add(alumno);                            
                }
            }
            LoadTable();
        } catch (Exception e) {
            System.out.println("Error "+e);
        }    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnCargar;
    private javax.swing.JButton jBttnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
