/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumno;

import com.mycompany.curso.ConsultaCurso;
import com.mycompany.curso.Curso;
import com.mycompany.loginpro.LoginPro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leo-progra
 */
public class MisCursos extends javax.swing.JFrame {
    /**
     * Creates new form MisCursos
     */
    ArrayList<Curso> listaCursosAsignados = new ArrayList<>();
    ArrayList<Curso> listaCursosNoAsignados = new ArrayList<>();
           
    public void cargarCursos(String carne){
        listaCursosAsignados.clear();
        listaCursosNoAsignados.clear();
        boolean setCurso = false;
        for (Curso curso : LoginPro.cursos) { //programacion, matematica
            setCurso = false;
            for (Alumno a : curso.getAlumnosCurso()) { //Recorriendo los alumnos que tiene matematica
                if (a.carne.equals(carne)) { //carne 2 -> 1
                    listaCursosAsignados.add(curso);
                    setCurso = true;
                    break;
                }
            }
            if (!setCurso) {   
                listaCursosNoAsignados.add(curso);
            }
        }
        
        if (!listaCursosAsignados.isEmpty()) { //true
            DefaultTableModel model = new DefaultTableModel(
            new String[]{"#","Nombre Curso","Seccion","Fecha Inicio", "Fecha Fin", "Profesor", "Nota"},
                listaCursosAsignados.size());
                jTable1.setModel(model);
                int row = 0;
            for (Curso c : listaCursosAsignados) {
                jTable1.setValueAt(row+1, row, 0);
                jTable1.setValueAt(c.getIdCurso()+"-"+ c.getNombre(), row, 1);
                jTable1.setValueAt(c.getSeccion(), row, 2);
                jTable1.setValueAt(c.getFechaInicio(), row, 3);
                jTable1.setValueAt(c.getFechaFin(), row, 4);
                jTable1.setValueAt(c.getNombreProfesor(), row, 5);
                for (Alumno l : c.alumnosCurso) {
                    if (l.carne.equals(alumnoLogeado.carne)) {
                        jTable1.setValueAt(l.nota, row, 6);
                    }
                }
                row++;
            }
        }else{
            DefaultTableModel model = new DefaultTableModel(
            new String[]{"#","Nombre Curso","Seccion","Fecha Inicio", "Fecha Fin", "Profesor"},
                listaCursosAsignados.size());
            jTable1.setModel(model);
        }
        
        if (!listaCursosNoAsignados.isEmpty()) {
            DefaultTableModel model = new DefaultTableModel(
            new String[]{"#","Nombre Curso","Seccion","Fecha Inicio", "Fecha Fin","Profesor"},
                listaCursosNoAsignados.size());
            jTable2.setModel(model);
            int row = 0;
            for (Curso c : listaCursosNoAsignados) {
                jTable2.setValueAt(row+1, row, 0);
                jTable2.setValueAt(c.getIdCurso()+"-"+c.getNombre(), row, 1);
                jTable2.setValueAt(c.getSeccion(), row, 2);
                jTable2.setValueAt(c.getFechaInicio(), row, 3);
                jTable2.setValueAt(c.getFechaFin(), row, 4);
                jTable2.setValueAt(c.getNombreProfesor(), row, 5);
                row++;
            }
        }else{
            DefaultTableModel model = new DefaultTableModel(
            new String[]{"#","Nombre Curso","Seccion","Fecha Inicio", "Fecha Fin", "Profesor"},
                listaCursosNoAsignados.size());
            jTable2.setModel(model);
        }
    }
    
    Alumno alumnoLogeado = null;
    
    public MisCursos(Alumno alumno) {
        initComponents();
        this.setTitle("Mis cursos asignados - "+alumno.nombre);
        alumnoLogeado = alumno;
        cargarCursos(alumno.carne);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Estos son los cursos que tienes asignados:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Desasignar Curso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cursos disponibles para asignarte:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Asignar Curso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane2)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int indiceSeleccionado = jTable1.getSelectedRow();
        if (indiceSeleccionado >= 0) {
            int idCurso = Integer.parseInt(jTable1.getValueAt(indiceSeleccionado, 1).toString().split("-")[0].trim());
            for (Curso curso : LoginPro.cursos) {
                if (curso.getIdCurso() == idCurso) {
                    curso.eliminarAlumno(alumnoLogeado.carne);
                    break;
                }
            }
            cargarCursos(alumnoLogeado.carne);
            for (Curso curso : LoginPro.cursos) {
                System.out.println("Estos son los alumnos ");
                if (curso.getIdCurso() == idCurso) {
                    for (Alumno alumno : curso.alumnosCurso) {
                        System.out.println(alumno.nombre+" "+alumno.nota);
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun curso");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BienvenidaAlumno ba = new BienvenidaAlumno();
        ba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int indiceSeleccionado = jTable2.getSelectedRow();
        Alumno alumnoSeleccionado = alumnoLogeado;
        Curso cursoSeleccionado = null;
        if (indiceSeleccionado >=0) {
            int idCurso = Integer.parseInt(jTable2.getValueAt(indiceSeleccionado, 1).toString().split("-")[0].trim());
            for (Curso curso : LoginPro.cursos) {
                if (curso.getIdCurso() == idCurso ) {
                    cursoSeleccionado = curso;
                    break;
                }
            }
            if (alumnoSeleccionado != null && cursoSeleccionado != null) {
                AsignaEstudiante ae = new AsignaEstudiante();
                String carne = alumnoSeleccionado.carne;
                String respuestaAsignacion = ae.AsignarEstudianteACurso(carne, idCurso);
                JOptionPane.showMessageDialog(this, respuestaAsignacion);
                cargarCursos(alumnoLogeado.carne);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun curso");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
