/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.curso;

import com.mycompany.curso.Curso;
import com.mycompany.curso.EdicionCursos;
import com.mycompany.loginpro.LoginPro;
import com.mycompany.profesor.Profesor;
import javax.swing.JOptionPane;

/**
 *
 * @author leo-progra
 */
public class EditaCurso extends javax.swing.JFrame {

    private Curso EditaCurso;
    
    public EditaCurso(int posicion) {
        initComponents();
        EditaCurso = LoginPro.cursos.get(posicion);
        jTxtFIdCurso.setText(String.valueOf(EditaCurso.idCurso));
        jTxtFNombreCurso.setText(EditaCurso.nombre);
        jTxtFSeccion.setText(EditaCurso.seccion);
        jTxtFFechaInicio.setText(EditaCurso.fechaInicio);
        jTxtFFechaFin.setText(EditaCurso.fechaFin);
        jTxtFHoraInicio.setText(EditaCurso.fechaInicio);
        jTxtFHoraFin.setText(EditaCurso.horaFin);
        
        jCmBProfesor.addItem(EditaCurso.nombreProfesor);
        for (Profesor p : LoginPro.profesores) {
            jCmBProfesor.addItem(p.nombre + " "+ p.apellido );
        }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtFIdCurso = new javax.swing.JTextField();
        jTxtFNombreCurso = new javax.swing.JTextField();
        jTxtFSeccion = new javax.swing.JTextField();
        jTxtFFechaInicio = new javax.swing.JTextField();
        jTxtFFechaFin = new javax.swing.JTextField();
        jTxtFHoraInicio = new javax.swing.JTextField();
        jTxtFHoraFin = new javax.swing.JTextField();
        jBtnRegresar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jCmBProfesor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Id Curso:");

        jLabel2.setText("Nombre Curso:");

        jLabel3.setText("Seccion:");

        jLabel4.setText("Fecha Inicio:");

        jLabel5.setText("Fecha Fin:");

        jLabel6.setText("Hora Inicio:");

        jLabel7.setText("Hora Fin:");

        jLabel8.setText("Profesor:");

        jTxtFIdCurso.setEnabled(false);

        jTxtFFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFFechaFinActionPerformed(evt);
            }
        });

        jBtnRegresar.setText("Regresar");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jCmBProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmBProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFNombreCurso)
                            .addComponent(jTxtFIdCurso)
                            .addComponent(jTxtFSeccion)
                            .addComponent(jTxtFFechaInicio)
                            .addComponent(jTxtFFechaFin)
                            .addComponent(jTxtFHoraInicio)
                            .addComponent(jTxtFHoraFin)
                            .addComponent(jCmBProfesor, 0, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnModificar)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtFIdCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtFNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtFSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtFFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtFFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxtFHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jTxtFHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCmBProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRegresar)
                    .addComponent(jBtnModificar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFFechaFinActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        EdicionCursos EdicionC = new EdicionCursos();
        EdicionC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        EditaCurso.idCurso = Integer.parseInt(jTxtFIdCurso.getText());
        EditaCurso.nombre = jTxtFNombreCurso.getText();
        EditaCurso.seccion = jTxtFSeccion.getText();
        EditaCurso.fechaInicio = jTxtFFechaInicio.getText();
        EditaCurso.fechaFin = jTxtFFechaFin.getText();
        EditaCurso.horaIncio = jTxtFHoraInicio.getText();
        EditaCurso.horaFin = jTxtFHoraFin.getText();
        
        String nombreSeleccionado = jCmBProfesor.getSelectedItem().toString();
        Profesor profesorEncontrado = null;
        for (Profesor p : LoginPro.profesores) {
            String nombreApellido = p.nombre+" "+p.apellido;
            if (nombreApellido.equals(nombreSeleccionado)) {
                profesorEncontrado = p;
                EditaCurso.nombreProfesor = nombreApellido;
            }
        }
        
        if (profesorEncontrado != null) {
            profesorEncontrado.cursoProfesor.add(EditaCurso);
        }
        JOptionPane.showMessageDialog(this, "Curso Modificado");
        EdicionCursos EdicionC = new EdicionCursos();
        EdicionC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jCmBProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmBProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmBProfesorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JComboBox<String> jCmBProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtFFechaFin;
    private javax.swing.JTextField jTxtFFechaInicio;
    private javax.swing.JTextField jTxtFHoraFin;
    private javax.swing.JTextField jTxtFHoraInicio;
    private javax.swing.JTextField jTxtFIdCurso;
    private javax.swing.JTextField jTxtFNombreCurso;
    private javax.swing.JTextField jTxtFSeccion;
    // End of variables declaration//GEN-END:variables
}
