/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.curso;

import com.mycompany.curso.Curso;
import com.mycompany.funciones.Funcionalidades;
import com.mycompany.funciones.ReglaAsignaciones;
import com.mycompany.loginpro.Administrador;
import com.mycompany.loginpro.LoginPro;
import com.mycompany.profesor.Profesor;
import javax.swing.JOptionPane;

/**
 *
 * @author leo-progra
 */
public class CrearCurso extends javax.swing.JFrame {

    /**
     * Creates new form CrearCurso
     */
    
    public void cargarCurso(){
        Funcionalidades f = new Funcionalidades();
        int idCurso = f.idIngreso("curso");
        jtxtIdCurso.setText(String.valueOf(idCurso));
    }
    
    public CrearCurso() {
        initComponents();
        this.setTitle("Crear Curso");
        cargarCurso();
        
        for (Profesor profe : LoginPro.profesores) {
            jCBProfesor.addItem(profe.nombre+" "+profe.apellido);
        }
        
        //Llenar inputs
        jtxtNombreCurso.setText("Programacion");
        jtxtSeccion.setText("A");
        jtxtFechaInicio.setText("01/05/2024");
        jtxtHoraInicio.setText("09:00");
        jtxtFechaFin.setText("31/05/2024");
        jtxtHoraFin.setText("11:00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBProfesor = new javax.swing.JComboBox<>();
        jBtnRegresac = new javax.swing.JButton();
        jBtnGuardarc = new javax.swing.JButton();
        jtxtIdCurso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombreCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtSeccion = new javax.swing.JTextField();
        jtxtFechaInicio = new javax.swing.JTextField();
        jtxtHoraInicio = new javax.swing.JTextField();
        jtxtFechaFin = new javax.swing.JTextField();
        jtxtHoraFin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jCBProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProfesorActionPerformed(evt);
            }
        });

        jBtnRegresac.setText("Regresar");
        jBtnRegresac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresacActionPerformed(evt);
            }
        });

        jBtnGuardarc.setText("Guardar");
        jBtnGuardarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarcActionPerformed(evt);
            }
        });

        jtxtIdCurso.setEnabled(false);
        jtxtIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Curso:");

        jLabel2.setText("Nombre Curso:");

        jLabel3.setText("Seccion:");

        jLabel4.setText("Fecha Inicio:");

        jLabel5.setText("Fecha Fin:");

        jLabel6.setText("Hora Inicio:");

        jLabel7.setText("Hora Fin:");

        jLabel8.setText("Elija un profesor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtFechaFin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtHoraInicio)
                    .addComponent(jtxtFechaInicio)
                    .addComponent(jtxtSeccion)
                    .addComponent(jtxtNombreCurso)
                    .addComponent(jtxtIdCurso)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnGuardarc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jBtnRegresac, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addComponent(jtxtHoraFin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jtxtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxtSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardarc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRegresac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProfesorActionPerformed
        
    }//GEN-LAST:event_jCBProfesorActionPerformed

    private void jBtnRegresacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresacActionPerformed
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresacActionPerformed

    private void jBtnGuardarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarcActionPerformed
        
        int idCursoF = Integer.parseInt(jtxtIdCurso.getText());
        String nombreF = jtxtNombreCurso.getText();
        String seccionF = jtxtSeccion.getText();
        String fechaInicioF = jtxtFechaInicio.getText();
        String fechaFinF = jtxtFechaFin.getText();
        String horaIncioF = jtxtHoraInicio.getText();
        String horaFinF = jtxtHoraFin.getText();
        String nombreProfeF = jCBProfesor.getSelectedItem().toString(); //jose lopez
        
        if (!nombreF.equals("") && !seccionF.equals("") && !fechaInicioF.equals("") && !nombreProfeF.equals("")) {
            Profesor profesorSeleccionado = null;
            for (Profesor profe : LoginPro.profesores) {
                String nombreProfesor = profe.nombre+" "+profe.apellido;
                if (nombreProfesor.equals(nombreProfeF)) {
                    System.out.println("Se asignara el curso al profesor");
                    profesorSeleccionado = profe;
                    break;
                }
            }
            
            //Creando asociacion de los cursos con el profesor
            if (profesorSeleccionado != null) {
                ReglaAsignaciones r = new ReglaAsignaciones();
                if (r.reglaProfesor(profesorSeleccionado.usuario)) {
                    //Agregando el curso creado al arraylist de cursos
                    Curso curso = new Curso(); //instacia de objeto curso
                    curso.idCurso=idCursoF;
                    curso.nombre=nombreF;
                    curso.seccion=seccionF;
                    curso.fechaInicio = fechaInicioF;
                    curso.fechaFin = fechaFinF;
                    curso.horaIncio = horaIncioF;
                    curso.horaFin = horaFinF;
                    curso.nombreProfesor=nombreProfeF;
                    LoginPro.cursos.add(curso);
                    profesorSeleccionado.cursoProfesor.add(curso);
                }else{
                    JOptionPane.showMessageDialog(null, "El profesor ya no puede llevar mas cursos");
                }
            }
            
            jtxtIdCurso.setText("");
            jtxtNombreCurso.setText("");
            jtxtSeccion.setText("");
            jtxtFechaInicio.setText("");
            jtxtFechaFin.setText("");
            jtxtHoraInicio.setText("");
            jtxtHoraFin.setText("");
            
            JOptionPane.showMessageDialog(null, "Se guardo el curso correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            cargarCurso();
            
        }else{
            JOptionPane.showMessageDialog(null, "No completo todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jBtnGuardarcActionPerformed

    private void jtxtIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdCursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardarc;
    private javax.swing.JButton jBtnRegresac;
    private javax.swing.JComboBox<String> jCBProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtxtFechaFin;
    private javax.swing.JTextField jtxtFechaInicio;
    private javax.swing.JTextField jtxtHoraFin;
    private javax.swing.JTextField jtxtHoraInicio;
    private javax.swing.JTextField jtxtIdCurso;
    private javax.swing.JTextField jtxtNombreCurso;
    private javax.swing.JTextField jtxtSeccion;
    // End of variables declaration//GEN-END:variables
}
