/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginpro;

import com.mycompany.profesor.Profesor;
import com.mycompany.alumno.Alumno;
import com.mycompany.curso.Curso;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leo-progra
 */
public class ConsultaEstCurso extends javax.swing.JFrame {

    public ConsultaEstCurso() {
        initComponents();
        this.setTitle("Consulta Cursos");
        for (Curso idc : LoginPro.cursos) {
            jCCursos.addItem(idc.idCurso+" - "+idc.nombre);
        }        
        if (jCCursos.getItemCount()>0) {
            jbtnBuscar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCCursos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombreProfesor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jCCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCursosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.setEnabled(false);
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Curso:");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Profesor asignado:");

        jtxtNombreProfesor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1)
                .addGap(94, 94, 94)
                .addComponent(jbtnBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNombreProfesor)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbtnBuscar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        int idCurso = Integer.parseInt(jCCursos.getSelectedItem().toString().split("-")[0].trim());//Se esta obteniendo el valor del Combobox y se le esta
        //asignando a curso buscado.
        Curso cursoSeleccionado = null;//Se esta decalarando una variable tipo curso, y se esta iniciando como nula.
        
        for (Curso curso : LoginPro.cursos) {
            if (idCurso == curso.idCurso) {//Esta comparando el valor que esta en jcombobox, con el nombre de cada curso.
                cursoSeleccionado = curso;
            }
        }
        //Buscar al profesor que tiene asignado el curso
        Profesor profesorASignado = null;
        for (Profesor profesor : LoginPro.profesores) {
            //System.out.println(profesor.nombre+" ====== ");
            for (Curso curso : profesor.cursoProfesor) {
                //System.out.println(curso.nombre+" ============ ");
                if (curso.idCurso == idCurso) {
                    profesorASignado = profesor;
                    break;
                }
            }
            if (profesorASignado != null) {
                jtxtNombreProfesor.setText(profesorASignado.nombre+" "+profesorASignado.apellido);
                break;
            }
        }
        
        if (cursoSeleccionado != null) {
            DefaultTableModel model = new DefaultTableModel(new String[] {"#", "Id Curso","Nombre", "Apellido", "Carne"}, cursoSeleccionado.alumnosCurso.size());
            jTable1.setModel(model);
            int row = 0;
            for (Alumno alumno : cursoSeleccionado.alumnosCurso) {
                jTable1.setValueAt(row+1, row, 0);
                jTable1.setValueAt(cursoSeleccionado.idCurso, row, 1);
                jTable1.setValueAt(alumno.nombre, row, 2);
                jTable1.setValueAt(alumno.apellido, row, 3);
                jTable1.setValueAt(alumno.carne, row, 4);
                row++;
            }
        }else{
            System.out.println("No ha seleccionado ningun curso");
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCursosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JTextField jtxtNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
