/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.profesor;

import com.mycompany.curso.Curso;
import com.mycompany.funciones.ReglaAsignaciones;
import com.mycompany.loginpro.Administrador;
import com.mycompany.loginpro.LoginPro;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.Buffer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo.castanaza
 */
public class CargaMasivaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form CargaMasivaProfesor
     */
    public CargaMasivaProfesor() {
        initComponents();
        ActualizarDatos();
        this.setTitle("Carga Masiva CSV de Profesores");
    }
    
    public void ActualizarDatos(){
        DefaultTableModel LlenaTablaCsv = new DefaultTableModel(new String[]{"Nombre","Apellido","Usuario","Password"},LoginPro.profesores.size());
            jTable1.setModel(LlenaTablaCsv);
            
            int row =0;
            
            for (Profesor l: LoginPro.profesores) {
                jTable1.setValueAt(l.nombre, row, 0);
                jTable1.setValueAt(l.apellido, row, 1);
                jTable1.setValueAt(l.usuario, row, 2);
                jTable1.setValueAt(l.password, row, 3);
                row ++;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Carga Masiva .CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Administrador RegresaMenu = new Administrador();
        RegresaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser archivo = new JFileChooser("");
        int seleccion = archivo.showDialog(this, "Cargar");
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            LecturaArchivoProfesor(archivo.getSelectedFile().toPath().toString());
        }
        JOptionPane.showMessageDialog(null, "Se realizo la carga masiva de forma exitosa!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void LecturaArchivoProfesor (String RutaConNombre){
        try {
            File file = new File(RutaConNombre);
            FileReader FileReader = new FileReader(file);
            
            BufferedReader br = new BufferedReader(FileReader);
            
            String linea;
            while ((linea=br.readLine())!=null){
                String[] contenidoLinea = linea.split(",");
                Profesor profesor = new Profesor();
                profesor.nombre = contenidoLinea[1];
                profesor.apellido = contenidoLinea[2];
                profesor.usuario = contenidoLinea[0];
                profesor.password = contenidoLinea[3];
                
                /*
                ReglaAsignaciones r = new ReglaAsignaciones();//regla
                if (r.reglaProfesor(contenidoLinea[0])) { //regla
                    int idCurso = Integer.parseInt(contenidoLinea[4]); //extra
                    Curso cursoSeleccionado = null; //extra
                    for (Curso curso : LoginPro.cursos) { //extra
                        if (curso.idCurso == idCurso) { //extra
                            System.out.println("Si encontre el curso");
                            cursoSeleccionado = curso; //extra
                            cursoSeleccionado.nombreProfesor = contenidoLinea[0]; //extra
                            break; //extra
                        } //extra
                    } //extra
                    if (cursoSeleccionado != null) { //extra
                        System.out.println("Agrego el curso al profesor");
                        profesor.cursoProfesor.add(cursoSeleccionado); //extra
                    } //extra
                    LoginPro.profesores.add(profesor);//regla
                }else{ //regla
                    JOptionPane.showConfirmDialog(null, "Este profesor no puede llevar mas cursos "+profesor.usuario); //regla
                } //regla
                */
                LoginPro.profesores.add(profesor);
            }
            ActualizarDatos();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
